# Site settings
title: My awesome title
email: #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome description for my new site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cperthuis.github.io" # the base hostname & protocol for your site
twitter_username: #
github_username:  cperthuis

# Build settings
markdown: kramdown
